version: '3'
services:
    app:
        container_name: seed
        restart: always
        build: .
        ports:
            - "3000:3000"
            - "3001:3001"
        links:
            - mongo
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"